### PR TITLE
Added .gitignore file

### PR DESCRIPTION
**Pull request by MeMeBallJM**
I noticed that you were committing your node_modules.
This pull request removes them from the repo; you can run:
```
npm install
```

### CODE REVIEW

**Review by veilm — APPROVED** [review]

**Review by veilm — CHANGES_REQUESTED** [review]
Fix typo in commit messages

**Comment by MeMeBallJM** [comment]
If you merge this request I will give you a 1L bottle of cherry naturally flavoured sparkling water.

It has 0 calories!!!!

**Comment by veilm** [comment]
LGTM 🚀

**Comment by ldoggy1208** [comment]
If this doesn't get merged I'm going to do unspeakable things to a family of 4

**Pull request merged**
